[package]
name = "rasterize"
version = "0.1.3"
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
description = "Simple and small 2D rendering library"
edition = "2021"
include = [
  "**/*.rs",
  "Cargo.toml",
  "README.md",
  "LICENSE",
  "paths/squirrel.png",
]
homepage = "https://github.com/aslpavel/rasterize"
repository = "https://github.com/aslpavel/rasterize.git"
license = "MIT"
readme = "README.md"
keywords = ["2d", "rendering"]
categories = ["rendering"]

[features]
default = []

[dependencies]
png = {version = "^0.16", optional = true}

[dev-dependencies]
criterion = "^0.3"
env_logger = "^0.7"
log = "^0.4"

[[bench]]
harness = false
name = "rasterize_bench"
